### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by katyhuff** [gyutaepark/cyclus#16]
- [x] Fork github.com/cyclus/cyclus.github.com
- [x] You want to edit this page :  http://fuelcycle.org/arche/toolkit.html
- [x] In the source branch and source directory, find arche/toolkit.rst and add a line at the very very bottom for your GIS mixin toolkit class!
- [x]  when your cyclus toolkit addition pull request is submitted, submit this PR simultaneosly (to the cyclus/cyclus.github.com repo).

**Comment by gyutaepark** [comment]
PR is submitted for gyutaepark/cyclus:gisDevelop and the website
